image:https://img.shields.io/github/license/ursjoss/kordamp-gradle-test-suite.svg[LICENSE, link=https://github.com/ursjoss/kordamp-gradle-test-suite/blob/master/LICENSE] image:https://github.com/ursjoss/kordamp-gradle-test-suite/workflows/Check/badge.svg?branch=master[Build Status, link=https://github.com/ursjoss/kordamp-gradle-test-suite/actions] image:https://sonarcloud.io/api/project_badges/measure?project=ursjoss_kordamp-gradle-test-suite&metric=alert_status[Quality Gate, link=https://sonarcloud.io/dashboard?id=ursjoss_kordamp-gradle-test-suite]

= Repository Description

This repo contains a number of gradle projects with the purpose of
testing several scenarios using the kordamp-gradle-plugin suite.

== Project 01: Java, Gradle (groovy)

Java project with three gradle submodules (configured using groovy),
the first one using both unit and integration tests to test some classes
in the main source set. The other two submodules depend on the first one
and integration-test (project2) or functional-test (project3) a production
class from project1.

== Project 02: Java, Gradle (kotlin DSL)

Java project with three gradle submodules (configured using kotlin DSL),
two of them depending on the first, testing the code of project1 both
using integration-tests and functional-tests.


== Project 03: Kotlin, Gralde (kotlin DSL)

kotlin project with three gradle submodules configured using kotlin DSL),
two of them depending on the first, testing the code of project1 both
using integration-tests and functional-tests.
