name: Check

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [01_java_gradle_groovy, 02_java_gradle_kotlin_dsl, 03_kotlin_gradle_kotlin_dsl, 04_license_reproducer]
        check: [check, allTests, aggregateJacocoMerge, aggregateJacocoReport, allJacocoReports, detekt, detekt aggregateDetekt, detekt sonarqube]
        exclude:
          - project: 01_java_gradle_groovy
            check: detekt
          - project: 01_java_gradle_groovy
            check: detekt aggregateDetekt
          - project: 01_java_gradle_groovy
            check: detekt sonarqube
          - project: 02_java_gradle_kotlin_dsl
            check: detekt
          - project: 02_java_gradle_kotlin_dsl
            check: detekt aggregateDetekt
          - project: 02_java_gradle_kotlin_dsl
            check: detekt sonarqube
          - project: 04_license_reproducer
            check: detekt sonarqube

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache global .gradle folder
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: global-gradle-${{ hashFiles('**/*.kt*') }}-${{ hashFiles('**/*.java') }}

      - name: Check with Gradle
        run: ./gradlew -p ${{ matrix.project }} clean ${{ matrix.check }} --no-daemon -Dsonar.organization=ursjoss-github
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
