name: Check

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [01_java_gradle_groovy, 02_java_gradle_kotlin_dsl, 03_kotlin_gradle_kotlin_dsl]
        check: [check, allTests, aggregateJacocoMerge, aggregateJacocoReport, allJacocoReports, detekt, aggregateDetekt]
        exclude:
          - project: 01_java_gradle_groovy
            check: detekt
          - project: 01_java_gradle_groovy
            check: aggregateDetekt
          - project: 02_java_gradle_kotlin_dsl
            check: detekt
          - project: 02_java_gradle_kotlin_dsl
            check: aggregateDetekt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache global .gradle folder
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: global-gradle-${{ hashFiles('**/*.kt*') }}-${{ hashFiles('**/*.java') }}

      - name: Check with Gradle
        run: ./gradlew -p ${{ matrix.project }} clean ${{ matrix.check }} --no-daemon
